[10057] [Planner] Treat empty int2vector as 1 dimensional
Problem:
Panic arise in the execution/optimization with empty int2vector's
```
ERROR:  internal error: internal error in optimizer: internal transform error
int2vector dimensions differ: got datum with dimension 0, expected dimension 1
```

Solution:
Introduce has_int2vector_dims which validates either the array is
1-dimensional, or 0 dimensional, and empty. Use this in 3 places where
checked

Testing:
New tests in int2vector.slt that test empty int2vector's, or rows with
empty vector's